# YOLO预测配置文件
# 用于包装检测预测任务

# 基础任务配置
task: detect  # 任务类型：detect(目标检测)

# 项目管理配置
# project: runs/predict  # 结果保存目录
project: mypack/valid  # 结果保存目录
# name: pack_predict  # 实验名称
name: labels
# 模型和数据配置
# 预训练模型路径 - 使用训练好的模型
model: /root/source/data2/hyg/projects/hs/runs/detect/pack_detection/weights/best.pt # 训练好的模型路径

# 数据源配置
source: mypack/valid/images  # 输入源：图片路径、目录、视频等

# 预测参数
imgsz: 640      # 输入图像尺寸
conf: 0.4      # 置信度阈值
iou: 0.45       # NMS IoU阈值
max_det: 100    # 每张图像最大检测数
device: 0       # 设备选择，使用第0号GPU
half: false     # 是否使用FP16半精度推理

# 输出配置
# save: true           # 保存预测结果图像
# save_json: true      # 保存结果到JSON文件
save_txt: true       # 保存结果为YOLO格式标注文件
exist_ok: false      # 是否允许覆盖已存在的实验目录

# 显示配置
show: true          # 是否显示预测结果
verbose: true        # 是否显示详细预测日志

# 其他配置
classes: null        # 指定检测的类别ID列表，null表示检测所有类别
agnostic_nms: false  # 是否使用类别无关的NMS
augment: false       # 推理时是否使用TTA
